#!/usr/bin/env python3
"""Convert the supplied path-only logo.svg into an Android adaptive vector icon.
The original SVG (including its metadata) is preserved unchanged.
"""
from pathlib import Path
import math
import re
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parent.parent
svg = ET.parse(root / 'logo.svg').getroot()
assert svg.get('viewBox') == '0 0 2048 2048', 'Review geometry if the source canvas changes'
paths = svg.findall('{http://www.w3.org/2000/svg}path')
assert len(paths) == 5 and paths[0].get('d') == 'M 0 0 L 2048 0 L 2048 2048 L 0 2048 L 0 0 z'
assert paths[0].get('fill') == 'rgb(252,252,252)'
foreground = paths[1:]
points = []
for path in foreground:
    assert path.get('transform') in (None, 'translate(0,0)')
    data = path.attrib['d']
    assert set(re.findall('[A-Za-z]', data)) <= set('MLCzZ'), 'Only absolute path coordinates supported'
    numbers = list(map(float, re.findall(r'-?\d+(?:\.\d+)?', data)))
    assert len(numbers) % 2 == 0
    points.extend(zip(numbers[::2], numbers[1::2]))
# All Bezier control points lie inside a 32 dp circle. By convexity, all curves
# fit inside Android's central 66 dp safe zone, including OEM circular masks.
radius = max(math.hypot(x-1024, y-1024) for x, y in points)
scale = 32 / radius
translate = 54 - 1024 * scale
android = 'http://schemas.android.com/apk/res/android'
ET.register_namespace('android', android)
def a(name): return f'{{{android}}}{name}'
def write(path, node):
    path.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(node, space='    ')
    path.write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate-icons.py from logo.svg. -->\n' + ET.tostring(node, encoding='unicode') + '\n')

res = root / 'app/src/main/res'
vector = ET.Element('vector', {a('width'): '108dp', a('height'): '108dp', a('viewportWidth'): '108', a('viewportHeight'): '108'})
group = ET.SubElement(vector, 'group', {a('scaleX'): f'{scale:.9f}', a('scaleY'): f'{scale:.9f}', a('translateX'): f'{translate:.9f}', a('translateY'): f'{translate:.9f}'})
for path in foreground:
    channels = tuple(map(int, re.fullmatch(r'rgb\((\d+),(\d+),(\d+)\)', path.attrib['fill']).groups()))
    ET.SubElement(group, 'path', {a('fillColor'): '#%02X%02X%02X' % channels, a('pathData'): path.attrib['d']})
write(res / 'drawable/ic_launcher_foreground.xml', vector)
for api in (26, 33):
    icon = ET.Element('adaptive-icon')
    ET.SubElement(icon, 'background', {a('drawable'): '@color/ic_launcher_background'})
    ET.SubElement(icon, 'foreground', {a('drawable'): '@drawable/ic_launcher_foreground'})
    if api >= 33:
        ET.SubElement(icon, 'monochrome', {a('drawable'): '@drawable/ic_launcher_foreground'})
    write(res / f'mipmap-anydpi-v{api}/ic_launcher.xml', icon)
colors = ET.Element('resources')
ET.SubElement(colors, 'color', {'name': 'ic_launcher_background'}).text = '#FCFCFC'
write(res / 'values/icon_colors.xml', colors)
print(f'Adaptive foreground: scale={scale:.9f}, radius=32 dp, centered on 108 dp layers')
