#!/usr/bin/env python3
"""Generate adaptive Android and rounded README icons from docs/logo.svg.
The original SVG (including its metadata) is preserved unchanged.
"""

from pathlib import Path
from copy import deepcopy
import math
import re
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parent.parent
svg = ET.parse(root / "docs/logo.svg").getroot()
assert svg.get("viewBox") == "0 0 2048 2048", "Review geometry if the source canvas changes"
paths = svg.findall("{http://www.w3.org/2000/svg}path")
assert len(paths) == 5 and paths[0].get("d") == "M 0 0 L 2048 0 L 2048 2048 L 0 2048 L 0 0 z"
assert paths[0].get("fill") == "rgb(252,252,252)"
foreground = paths[1:]
points = []
for path in foreground:
    assert path.get("transform") in (None, "translate(0,0)")
    data = path.attrib["d"]
    assert set(re.findall("[A-Za-z]", data)) <= set("MLCzZ"), (
        "Only absolute path coordinates supported"
    )
    numbers = list(map(float, re.findall(r"-?\d+(?:\.\d+)?", data)))
    assert len(numbers) % 2 == 0
    points.extend(zip(numbers[::2], numbers[1::2]))
left, right = min(x for x, _ in points), max(x for x, _ in points)
top, bottom = min(y for _, y in points), max(y for _, y in points)
center_x, center_y = (left + right) / 2, (top + bottom) / 2
# Remove the source canvas padding, then fit the artwork to the central 66 dp
# safe circle. Bezier curves stay inside their control-point convex hulls.
# A 0.1 dp inset accommodates coordinate rounding without extra visual padding.
radius = max(math.hypot(x - center_x, y - center_y) for x, y in points)
scale = 32.9 / radius
translate_x, translate_y = 54 - center_x * scale, 54 - center_y * scale
android = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", android)


def a(name):
    return f"{{{android}}}{name}"


def write(path, node):
    path.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(node, space="    ")
    path.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate-icons.py from docs/logo.svg. -->\n'
        + ET.tostring(node, encoding="unicode")
        + "\n"
    )


res = root / "app/src/main/res"
vector = ET.Element(
    "vector",
    {
        a("width"): "108dp",
        a("height"): "108dp",
        a("viewportWidth"): "108",
        a("viewportHeight"): "108",
    },
)
group = ET.SubElement(
    vector,
    "group",
    {
        a("scaleX"): f"{scale:.9f}",
        a("scaleY"): f"{scale:.9f}",
        a("translateX"): f"{translate_x:.9f}",
        a("translateY"): f"{translate_y:.9f}",
    },
)
for path in foreground:
    channels = tuple(
        map(int, re.fullmatch(r"rgb\((\d+),(\d+),(\d+)\)", path.attrib["fill"]).groups())
    )
    ET.SubElement(
        group, "path", {a("fillColor"): "#%02X%02X%02X" % channels, a("pathData"): path.attrib["d"]}
    )
write(res / "drawable/ic_launcher_foreground.xml", vector)
for api in (26, 33):
    icon = ET.Element("adaptive-icon")
    ET.SubElement(icon, "background", {a("drawable"): "@color/ic_launcher_background"})
    ET.SubElement(icon, "foreground", {a("drawable"): "@drawable/ic_launcher_foreground"})
    if api >= 33:
        ET.SubElement(icon, "monochrome", {a("drawable"): "@drawable/ic_launcher_foreground"})
    folder = "mipmap-anydpi" if api == 26 else f"mipmap-anydpi-v{api}"
    write(res / folder / "ic_launcher.xml", icon)
colors = ET.Element("resources")
ET.SubElement(colors, "color", {"name": "ic_launcher_background"}).text = "#FCFCFC"
write(res / "values/icon_colors.xml", colors)
print(f"Adaptive foreground: scale={scale:.9f}, radius=32.9 dp, centered on 108 dp layers")

# GitHub sanitizes inline CSS. Round the SVG background itself, leaving
# transparent corners, and use a tighter crop than the launcher safe area.
svg_ns = "http://www.w3.org/2000/svg"
ET.register_namespace("", svg_ns)


def s(name):
    return f"{{{svg_ns}}}{name}"


readme = ET.Element(
    s("svg"),
    {
        "viewBox": "0 0 256 256",
        "width": "256",
        "height": "256",
        "role": "img",
        "aria-labelledby": "title",
    },
)
ET.SubElement(readme, s("title"), {"id": "title"}).text = "NFS SAF"
readme.append(ET.Comment(" Generated from docs/logo.svg by scripts/generate-icons.py. "))
ET.SubElement(readme, s("rect"), {"width": "256", "height": "256", "rx": "52", "fill": "#FCFCFC"})
readme_scale = 224 / max(right - left, bottom - top)
group = ET.SubElement(
    readme,
    s("g"),
    {
        "transform": f"translate({128 - center_x * readme_scale:.6f} {128 - center_y * readme_scale:.6f}) scale({readme_scale:.9f})"
    },
)
for path in foreground:
    group.append(deepcopy(path))
ET.indent(readme, space="  ")
(root / "docs/logo-readme.svg").write_text(ET.tostring(readme, encoding="unicode") + "\n")
print("README logo: rounded background, 16 px horizontal padding on a 256 px canvas")
